#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

POLICY_DIR="$(dirname ${BASH_SOURCE[0]})"

# Build the Open Policy Agent policy WebAssembly module (.wasm) from the .rego files
opa build -t wasm \
    -e 'terraform' \
    -e 'terraform/no_changes' \
    -e 'terraform/resource_changes' \
    -e 'terraform/output_changes' "$POLICY_DIR"
tar -xzf bundle.tar.gz /policy.wasm
mv policy.wasm "$POLICY_DIR"
rm bundle.tar.gz

# Base 64 encode and write the policy.js that is used by the action
POLICY_BASE64="$(base64 $POLICY_DIR/policy.wasm)"
echo "
\"use strict\"
// Auto-generated by 'npm run policy'
module.exports = {
  policyWasmBase64: \"${POLICY_BASE64}\",
};
" > "$POLICY_DIR"/policy.js
