on: [issues, pull_request, workflow_dispatch]
jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: Sync repository labels
    steps:
      - uses: cds-snc/labels@ce105ff4bd1e1359ef73adf873338df45ce148bd # v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}