name: S3 backup
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  s3-backup:
    runs-on: ubuntu-latest
    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        fetch-depth: 0 # retrieve all history
        persist-credentials: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        role-to-assume: ${{ secrets.AWS_S3_BACKUP_IAM_ROLE_ARN }}
        role-session-name: S3Backup
        aws-region: ca-central-1

    - name: Upload zip to S3 bucket
      run: |
        ZIP_FILE=`basename ${{ github.repository }}`-`date '+%Y-%m-%d'`.zip
        zip -rq "${ZIP_FILE}" .
        aws s3 cp "${ZIP_FILE}" s3://${{ secrets.AWS_S3_BACKUP_BUCKET }}/${{ github.repository }}/"${ZIP_FILE}"

    - name: Notify Slack channel if this job failed
      if: ${{ failure() }}
      run: |
        json='{"text":"S3 backup failed in <https://github.com/${{ github.repository }}>!"}'
        curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_NOTIFY_WEBHOOK }}
